kind: pipeline
name: test

steps:
  - name: cookstyle
    image: chef/chefworkstation
    commands:
      - cookstyle .

  - name: rspec
    image: chef/chefworkstation
    environment:
      CHEF_LICENSE: accept
    commands:
      - chef exec rspec . --format documentation

trigger:
  event:
    exclude:
      - promote

---
kind: pipeline
name: build and upload

globals:
  - &drone_vars
    AZURE_STORAGE_ACCOUNT_NAME:
      from_secret: AZ_STORAGE_ACCOUNT_NAME
    AZURE_STORAGE_CONTAINER_NAME:
      from_secret: AZ_STORAGE_CONTAINER_NAME
    AZURE_STORAGE_SAS_TOKEN:
      from_secret: AZ_STORAGE_SAS_TOKEN
    CHEF_LICENSE: accept

steps:
  - name: build artifact
    image: chef/chefworkstation
    environment:
      <<: *drone_vars
    commands:
      - chef install
      - chef export . -a
      - for filename in *.tgz; do mv "$filename" "${DRONE_BUILD_NUMBER}-$filename"; done;
      - ls -al

  - name: upload artifact
    image: mcr.microsoft.com/azure-cli
    environment:
      <<: *drone_vars
    commands:
      - ls -al
      - ARTIFACT_NAME="$(ls | grep *.tgz)"
      - echo $ARTIFACT_NAME
      - az storage blob upload --file $ARTIFACT_NAME --name $ARTIFACT_NAME --account-name 'droneteststorage98' --container-name 'policytar' --sas-token 'sp=rwl&st=2021-02-18T04:18:57Z&se=2021-03-17T11:18:57Z&spr=https&sv=2020-02-10&sr=c&sig=heab0mxhGw38Id4CXhlSOxlZM8cp2zk8g%2FDA1ts8nyE%3D' 
      # - az storage blob upload --file $ARTIFACT_NAME --name $ARTIFACT_NAME --container-name $AZURE_STORAGE_CONTAINER_NAME --account-name $AZURE_STORAGE_ACCOUNT_NAME --sas-token $AZURE_STORAGE_SAS_TOKEN

trigger:
  branch:
    - main
  event:
    - push

depends_on:
  - test