name 'winstacks'
maintainer 'MAN98'
maintainer_email 'allanbernardo98@outlook.com'
license 'All Rights Reserved'
description 'Installs/Configures winstacks'
supports 'windows'
issues_url 'https://github.com/98Solutions/chefwindowspolicy/issues'
source_url 'https://github.com/98Solutions/chefwindowspolicy'
version '0.1.0'
chef_version '>= 15.0'
